//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface AddCarDTO {
    carName?: string | undefined;
    carModel?: string | undefined;
    carClass?: string | undefined;
    carEngine?: string | undefined;
    carAmount?: number;
    carPrice?: number;
    moTa?: string | undefined;
    head1?: string | undefined;
    moTa2?: string | undefined;
}

export interface AddCarDetailDTO {
    carId?: string;
    head1?: string | undefined;
    title1?: string | undefined;
    head2?: string | undefined;
    title2?: string | undefined;
    head3?: string | undefined;
    title3?: string | undefined;
}

export interface AddCartDTO {
    customerId?: string;
    carId?: string;
    amount?: number | undefined;
    price?: number | undefined;
}

export interface AddOrderDTO {
    carId?: string;
    customerId?: string;
    orderDate?: Date;
    orderStatus?: string | undefined;
    amount?: number;
    totalPrice?: number;
}

export interface CarDTO {
    carId?: string;
    carName?: string | undefined;
    carModel?: string | undefined;
    carClass?: string | undefined;
    carEngine?: string | undefined;
    carAmount?: number;
    carPrice?: number;
    moTa?: string | undefined;
    head1?: string | undefined;
    moTa2?: string | undefined;
}

export interface CarDetailDTO {
    detailId?: string;
    carId?: string;
    head1?: string | undefined;
    title1?: string | undefined;
    head2?: string | undefined;
    title2?: string | undefined;
    head3?: string | undefined;
    title3?: string | undefined;
}

export interface CartDTO {
    cartId?: string;
    customerId?: string;
    carId?: string;
    amount?: number | undefined;
    price?: number | undefined;
}

export interface CartNotiDTO {
    carName?: string | undefined;
    amount?: number;
    price?: number;
}

export interface ChangeInfoDTO {
    customerName?: string | undefined;
    customerPhone?: string | undefined;
    customerAddress?: string | undefined;
    customerDate?: Date;
    customerLicense?: string | undefined;
    customerEmail?: string | undefined;
}

export interface ChangePasswordDTO {
    oldPassword?: string | undefined;
    newPassword?: string | undefined;
}

export interface CustomerCartDTO {
    totalAmount?: number | undefined;
    totalDiscount?: number | undefined;
}

export interface CustomerCreateDTO {
    customerName?: string | undefined;
    customerEmail?: string | undefined;
    customerPassword?: string | undefined;
}

export interface CustomerDTO {
    customerId?: string;
    customerName?: string | undefined;
    customerPhone?: string | undefined;
    customerAddress?: string | undefined;
    customerDate?: Date;
    customerLicense?: string | undefined;
    customerEmail?: string | undefined;
    customerPassword?: string | undefined;
}

export interface CustomerLoginDTO {
    email?: string | undefined;
    password?: string | undefined;
    token?: string | undefined;
    admin?: boolean | undefined;
}

export interface CustomerOrderDTO {
    orderId?: string;
    carId?: string;
    carName?: string | undefined;
    carModel?: string | undefined;
    carClass?: string | undefined;
    carEngine?: string | undefined;
    customerId?: string;
    orderDate?: Date;
    orderStatus?: string | undefined;
    amount?: number;
    totalPrice?: number;
}

export interface CustomerPaymentDTO {
    customerId?: string;
    orderStatus?: string | undefined;
}

export interface CustomerTokenDTO {
    token?: string | undefined;
    id?: string;
    email?: string | undefined;
    name?: string | undefined;
    password?: string | undefined;
    admin?: boolean | undefined;
}

export interface OrderDTO {
    orderId?: string;
    carId?: string;
    customerId?: string;
    orderDate?: Date;
    orderStatus?: string | undefined;
    amount?: number;
    totalPrice?: number;
}

export interface QuickAddCartDTO {
    customerId?: string;
    carId?: string;
}

export interface UpdateCarDetailDTO {
    head1?: string | undefined;
    title1?: string | undefined;
    head2?: string | undefined;
    title2?: string | undefined;
    head3?: string | undefined;
    title3?: string | undefined;
}

export interface UpdateOrderDTO {
    orderDate?: Date;
    orderStatus?: string | undefined;
    amount?: number;
    totalPrice?: number;
}